[package]
name = "gpio-utils"
version = "0.1.0"
authors = ["Paul Osborne <osbpau@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://github.com/rust-embedded/gpio-utils"
keywords = ["gpio", "linux", "sysfs_gpoi", "cli", "command-line"]
description = """
Command-line utilities for interacting with GPIOs under Linux

This wraps the `sysfs_gpio` crate in a form usable by both
Rust applications or any other applications.
"""

[dependencies]
clap = "2.2"
rustc-serialize = "0.3"
sysfs_gpio = "0.4"
toml = "0.1"
glob = "0.2"
log = "0.3"
env_logger = "0.3"
retry = "0.4.0"

[dependencies.clippy]
version = "0.0"
optional = true

[features]
default = []
lints = ["clippy"]

[[bin]]
name = "gpio"
path = "src/main.rs"
